name: Publish Docker Image to GitHub Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest

    outputs:
      base_dockerfile: ${{ steps.changes.outputs.base_dockerfile }}
      dockerfile: ${{ steps.changes.outputs.dockerfile }}

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            base_dockerfile:
              - base.Dockerfile
            dockerfile:
              - Dockerfile
          base: main

  construct-image-names:
    name: Construct Image Names
    needs: changes
    if: needs.changes.outputs.base_dockerfile == 'true' || needs.changes.outputs.dockerfile == 'true'
    runs-on: ubuntu-latest

    outputs:
      base_image_name: ${{ steps.image_names.outputs.base_image_name }}
      image_name: ${{ steps.image_names.outputs.image_name }}

    steps:
      - name: Construct image names
        id: image_names
        run: |
          export LOWERCASE_REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo "base_image_name=$LOWERCASE_REPO_NAME-base" >> $GITHUB_OUTPUT
          echo "image_name=$LOWERCASE_REPO_NAME" >> $GITHUB_OUTPUT

  build-and-push-base-image:
    name: Build and Push Base Image
    needs: [changes, construct-image-names]
    if: needs.changes.outputs.base_dockerfile == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ needs.construct-image-names.outputs.base_image_name }}
          tags: |
            latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: base.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-and-push-image:
    name: Build and Push Image
    needs: [changes, construct-image-names, build-and-push-base-image]
    if: always() && needs.changes.outputs.dockerfile == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ needs.construct-image-names.outputs.image_name }}
          tags: |
            latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          build-args: |
            BASE_IMAGE=${{ env.REGISTRY }}/${{ needs.construct-image-names.outputs.base_image_name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
